NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('simpleapp.urls')),
]

NewsPaper/accounts/urls.py
from django.urls import path
from .views import SignUp

urlpatterns = [
    path('signup', SignUp.as_view(), name="signup"),
]

NewsPaper/simpleapp/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', ProductsList.as_view(), name='product_list'),
    path('<int:pk>', ProductDetail.as_view(), name='product_detail'),
    path('multiply/', multiply),
    path('create/', ProductCreate.as_view(), name='product_create'),
    path('<int:pk>/update/', ProductUpdate.as_view(), name='product_update'),
    path('<int:pk>/delete/', ProductDelete.as_view(), name='product_delete'),
]

NewsPaper/accounts/models.py
from django.db import models

# Create your models here.

NewsPaper/simpleapp/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
    )
    description = models.TextField()
    quantity = models.IntegerField(
        validators=[MinValueValidator(0)],
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='products',
    )
    price = models.FloatField(
        validators=[MinValueValidator(0.0)],
    )

    material = models.ForeignKey(
        to='Material',
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return f'{self.name.title()}: {self.description[:20]}'

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])


class Material(models.Model):
    name = models.CharField(
        unique=True,
        max_length=255,
    )

    def __str__(self):
        return self.name


class ProductMaterial(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)


class Category(models.Model):
    name = models.CharField(
        unique=True,
        max_length=100,
    )

    def __str__(self):
        return self.name.title()

NewsPaper/accounts/forms.py
# from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
#
#
# class SignUpForm(UserCreationForm):
#     email = forms.EmailField(label="Email")
#     first_name = forms.CharField(label="Имя")
#     last_name = forms.CharField(label="Фамилия")
#
#     class Meta:
#         model = User
#         fields = (
#             "username",
#             "first_name",
#             "last_name",
#             "email",
#             "password1",
#             "password2",
#         )

from allauth.account.forms import SignupForm
from django.core.mail import EmailMultiAlternatives


class CustomSignupForm(SignupForm):
    def save(self, request):
        user = super().save(request)

        subject = 'Добро пожаловать в наш интернет магазин!'
        text = f'{user.username}, вы успешно зарегистрировались!'
        html = (
            f'<b>{user.username}</b>, Вы успешно зарегистрировались на '
            f'<a href="http://127.0.0.1:8000/products">сайте</a>!'
        )
        msg = EmailMultiAlternatives(
            subject=subject, body=text, from_email=None, to=[user.email]
        )
        msg.attach_alternative(html, "text/html")
        msg.send()

        return user

NewsPaper/simpleapp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Product


class ProductForm(forms.ModelForm):
    description = forms.CharField(min_length=20)

    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'price', 'quantity']

    def clean(self):
        cleaned_data = super().clean()
        description = cleaned_data.get("description")
        name = cleaned_data.get("name")

        if name == description:
            raise ValidationError(
                "Описание не должно быть идентично названию."
            )

        return cleaned_data

NewsPaper/accounts/views.py
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from .forms import SignUpForm


class SignUp(CreateView):
    model = User
    form_class = SignUpForm
    success_url = '/accounts/login'
    template_name = 'registration/signup.html'

NewsPaper/simpleapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .filters import ProductFilter
from .forms import ProductForm
from .models import Product
from django.http import HttpResponse, HttpResponseRedirect
import logging

logger = logging.getLogger(__name__)


class ProductsList(ListView):
    model = Product
    ordering = 'name'
    template_name = 'products.html'
    context_object_name = 'products'
    paginate_by = 2

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = ProductFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class ProductDetail(DetailView):
    model = Product
    template_name = 'product.html'
    context_object_name = 'product'


def multiply(request):
    number = request.GET.get('number')
    multiplier = request.GET.get('multiplier')

    try:
        result = int(number) * int(multiplier)
        html = f'<html><body>{number}*{multiplier}={result}</body></html>'
    except (ValueError, TypeError):
        html = '<html><body>Invalid input.</body></html>'
    return HttpResponse(html)


class ProductCreate(PermissionRequiredMixin, CreateView):
    raise_exception = True
    form_class = ProductForm
    model = Product
    template_name = 'product_edit.html'


class ProductUpdate(PermissionRequiredMixin, UpdateView):
    form_class = ProductForm
    model = Product
    template_name = 'product_edit.html'


class ProductDelete(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = 'product_delete.html'
    success_url = reverse_lazy('product_list')

NewsPaper/templates/article_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Статья</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/article_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_censor %}
{% load custom_tags %}

{% block title %}
ALL NEWS
{% endblock title %}

{% if post %}
    {% block content %}
        <h1>ALL NEWS</h1>
        <p>Всего статей: {{ post|length }}</p>
        <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

        </br>
            <ul class="nobullet">
                {% for i in post %}
                <h2>{{ i.title|filter_message }}</h2>
                <p>{{ i.dateCreate|date:'d M Y' }}</p>
                <p>{{ i.text|truncatewords:15|filter_message }}</p>
                <hr>
                {% endfor %}
            </ul>
{% if page_obj.has_previous %}
<a href="?{% url_replace page=1 %}">1</a>
{% if page_obj.previous_page_number != 1 %}
...
<a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
{% endif %}
{% endif %}

   {{ page_obj.number }}

{% if page_obj.has_next %}
<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
{% endif %}
{% endif %}


{% endblock content %}

{% else %}
    <h1>Новостей нет!</h1>>
{% endif %}

NewsPaper/templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_censor %}

{% block title %}
NEWS
{% endblock title %}

{% block content %}
    <h1>{{ onepost.title }}</h1>
    <p>{{ onepost.dateCreate|date:'d M Y' }}</p>
    <p>{{ onepost.text }}</p>
{% endblock content %}

NewsPaper/templates/product.html
{% extends 'flatpages/default.html' %}

{% block title %}
Product
{% endblock title %}

{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

NewsPaper/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/product_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/products.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Products
{% endblock title %}

{% block content %}
    <h1>Все товары</h1>
    <form action="" method="get" >
    {{ filterset.form.non_field_errors }}

    {{ filterset.form.name__icontains.errors }}
    <label for="{{ filterset.form.name__icontains.id_for_label }}">Search</label>
    <input
        id="{{ filterset.form.name__icontains.id }}"
        name="{{ filterset.form.name__icontains.name }}"
        value="{{ filterset.form.name__icontains.value }}"
        class="form-control"
    >
    <input type="submit" class="mt-3 btn-primary" value="Найти" />
</form>
    <hr>

    {% if perms.simpleapp.add_product %}
    <a href="{% url 'product_create' %}">Добавить товар</a>
    {% endif %}
    {% if products %}
        <table>
            <tr>
                <td>Название</td>
                <td>Описание</td>
                <td>Категория</td>
                <td>Цена</td>
                <td>Количество</td>

                {% if perms.simpleapp.change_product or perms.simpleapp.delete_product %}
                <td>Действия</td>
                {% endif %}

            </tr>

            {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.description|truncatewords:15 }}</td>
                <td>{{ product.category.name }}</td>
                <td>{{ product.price|currency }}</td>
                <td>{{ product.quantity }}</td>
                <td>{% if perms.simpleapp.change_product %}
                <a href="{% url 'product_update' pk=product.id %}">Изменить</a>
                {% endif %}
                {% if perms.simpleapp.delete_product %}
                <a href="{% url 'product_delete' product.id %}">Удалить</a>
                {% endif %}
                </td>

            </tr>
            {% endfor %}

        </table>
    {% else %}
        <h2>Товаров нет</h2>
    {% endif %}

{% if page_obj.has_previous %}
    <a href="?{% url_replace page=1 %}>1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{{ page_obj.number }}

{% if page_obj.has_next %}
    <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page.obj.next_page_number %}
    ...
        <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}
{% endblock content %}